# DVMC: DVM Client-VM Connector API.
# Copyright 2022 blastdoor7
# Licensed under the Apache License, Version 2.0.

[package]
name = "dvmc-declare"
version = "10.0.0-alpha.5"
authors = ["Jake Lang <jak3lang@gmail.com>", "Alex Beregszaszi <alex@rtfs.hu>"]
license = "Apache-2.0"
repository = "https://github.com/blastdoor7/dvmc"
description = "Bindings to DVMC (VM declare macro)"
edition = "2018"

[dependencies]
quote = "1.0"
heck = "0.3.1"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
# For documentation trans_logs
dvmc-vm = { path = "../dvmc-vm", version = "10.0.0-alpha.5" }

[lib]
proc-macro = true
