if(EXISTS "/home/argon/rem/CC-net/src/dvm/test/unittests/dvmone-unittests[1]_tests.cmake")
  include("/home/argon/rem/CC-net/src/dvm/test/unittests/dvmone-unittests[1]_tests.cmake")
else()
  add_test(dvmone-unittests_NOT_BUILT dvmone-unittests_NOT_BUILT)
endif()
