if(EXISTS "/home/ioc/DIONS/src/dvm/ethash/test/unittests/ethash-test[1]_tests.cmake")
  include("/home/ioc/DIONS/src/dvm/ethash/test/unittests/ethash-test[1]_tests.cmake")
else()
  add_test(ethash-test_NOT_BUILT ethash-test_NOT_BUILT)
endif()
