# DVMC: DVM Client-VM Connector API.
# Copyright 2022 blastdoor7
# Licensed under the Apache License, Version 2.0.

[package]
name = "trans_log-rust-vm"
version = "10.0.0-alpha.5"
authors = ["Alex Beregszaszi <alex@rtfs.hu>", "Jake Lang <jak3lang@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "trans_logrustvm"
crate-type = ["staticlib", "cdylib"]

[dependencies]
dvmc-sys = { path = "../../bindings/rust/dvmc-sys" }
dvmc-vm = { path = "../../bindings/rust/dvmc-vm" }
dvmc-declare = { path = "../../bindings/rust/dvmc-declare" }
