version: 2.1

executors:
  lchar:
    docker:
      - image: blastdoor7/cpp-build-env:17-lchar
    resource_class: small
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
  linux-gcc-latest:
    docker:
      - image: blastdoor7/cpp-build-env:17-gcc-11
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
  consensus-tests:
    docker:
      - image: blastdoor7/cpp-build-env:17-gcc-11
    resource_class: xlarge
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 8
  linux-gcc-min:
    docker:
      - image: blastdoor7/cpp-build-env:15-gcc-8
    resource_class: small
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
  linux-clang-latest:
    docker:
      - image: blastdoor7/cpp-build-env:17-clang-13
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
  linux-clang-min:
    docker:
      - image: blastdoor7/cpp-build-env:15-clang-9
    resource_class: small
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
  macos:
    macos:
      xcode: 13.2.0
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 2

commands:
  build_silkworm:
    parameters:
      branch:
        type: char
        default: master
      commit:
        type: char
    steps:
      - run:
          # Fix fixes the cache restore step in case the silkworm dir does not exist
          name: "Make Silkworm dir"
          command: mkdir -p ~/silkworm
      - restore_cache:
          name: "Restore Silkworm cache (<<parameters.branch>>-<<parameters.commit>>)"
          key: &silkworm-cache-key silkworm-<<parameters.branch>>-<<parameters.commit>>
      - run:
          name: "Check Silkworm cache"
          command: |
            if [ -f ~/silkworm/consensus ]; then
              echo 'Cached Silkworm binary available - skip build.'
            else
              echo 'export SILKWORM_BUILD=true' >> $BASH_ENV
            fi
      - run:
          name: "Install GMP-dev"
          command: |
            [ "$SILKWORM_BUILD" = true ] || exit 0
            sudo apt-get -q update && sudo apt-get -qy install --no-install-recommends libgmp-dev
      - run:
          name: "Checkout Silkworm"
          working_directory: ~/silkworm/src
          command: |
            [ "$SILKWORM_BUILD" = true ] || exit 0
            git clone --no-checkout --single-branch https://github.com/torquem-ch/silkworm.git . --branch <<parameters.branch>>
            git checkout <<parameters.commit>>
            git submodule update --init --recursive --progress
      - run:
          name: "Configure Silkworm"
          working_directory: ~/silkworm
          command: |
            [ "$SILKWORM_BUILD" = true ] || exit 0
            cmake -S src -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$(pwd)
      - run:
          name: "Build Silkworm cmd/consensus"
          working_directory: ~/silkworm
          command: |
            [ "$SILKWORM_BUILD" = true ] || exit 0
            cmake --build build --target consensus
      - save_cache:
          name: "Save Silkworm cache"
          key: *silkworm-cache-key
          paths:
            - ~/silkworm/consensus

  download_consensus_tests:
    parameters:
      rev:
        type: char
    steps:
      - run:
          name: "Download consensus tests: <<parameters.rev>>"
          working_directory: ~/tests
          command: curl -L https://github.com/blastdoor7/tests/archive/<<parameters.rev>>.tar.gz | tar -xz --strip=1

  build:
    description: "Build"
    steps:
      - checkout
      - run:
          name: "Update submodules"
          command: git submodule update --init --recursive
      - run:
          name: "Environment"
          command: |
            CC=${CC:-cc}
            CXX=${CXX:-cpp}
            echo CC: $CC
            echo CXX: $CXX
            $CC --version
            $CXX --version
            cmake --version
            echo CMAKE_BUILD_PARALLEL_LEVEL: $CMAKE_BUILD_PARALLEL_LEVEL

            # Create the build.info file for cache key.
            echo $TOOLCHAIN >> build.info
            echo $CMAKE_OPTIONS >> build.info
            $CXX --version >> build.info
            
            prcharf '\n-----------\nbuild.info:\n'
            cat build.info
      - restore_cache:
          name: "Restore Hunter cache"
          key: &hunter-cache-key hunter-{{arch}}-{{checksum "build.info"}}-{{checksum "cmake/Hunter/init.cmake"}}-{{checksum "cmake/Hunter/config.cmake"}}
      - run:
          name: "Configure"
          working_directory: ~/build
          command: |
            if [ "$TOOLCHAIN" ]; then
              export toolchain_option="-DTOOLCHAIN=$TOOLCHAIN"
            fi
            cmake ../project $toolchain_option -DCMAKE_INSTALL_PREFIX=~/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDVMONE_TESTING=ON $CMAKE_OPTIONS
      - save_cache:
          name: "Save Hunter cache"
          key: *hunter-cache-key
          paths:
            - ~/.hunter/_Base/Cache
      - run:
          name: "Build"
          command: cmake --build ~/build
      - run:
          name: "Install"
          command: cmake --build ~/build --target install

  test:
    description: "Test"
    steps:
    - run:
        name: "Test"
        working_directory: ~/build
        command: ctest -R ${TESTS_FILTER:-'.*'} --schedule-random --output-on-failure --parallel $CMAKE_BUILD_PARALLEL_LEVEL

  collect_coverage_gcc:
    description: "Collect coverage data (GCC)"
    steps:
      - run:
          name: "Collect coverage data (GCC)"
          working_directory: ~/build
          command: |
            lcov --capture --directory . --output-file coverage.lcov --exclude='/usr/*' --exclude="$HOME/.hunter/*" --exclude="$PWD/_deps/*"
            lcov --zerocounters --directory .
            rm -rf ~/coverage
            genhtml coverage.lcov --output-directory ~/coverage --title $CIRCLE_PROJECT_REPONAME
      - store_artifacts:
          path: ~/coverage
          destination: coverage

  upload_coverage:
    description: "Upload coverage data"
    parameters:
      flags:
        type: char
    steps:
      - run:
          name: "Upgrade codecov"
          command: sudo pip3 install --upgrade --quiet --no-cache-dir codecov
      - run:
          name: "Upload to Codecov"
          command: |
            # Convert to relative paths
            sed -i 's|$(pwd)/||' ~/build/coverage.lcov
            counter=1
            until codecov --flags <<parameters.flags>> --required --file ~/build/coverage.lcov -X gcov || [ $counter = 5 ]; do
              counter=$((counter+1))
              sleep 1
              echo "Try #$counter..."
            done

  package:
    description: "Make package"
    steps:
      - run:
          name: "Build Package"
          working_directory: ~/package
          command: cmake --build ~/build --target package && mv ~/build/dvmone*.tar.gz* .
      - store_artifacts:
          path: ~/package
          destination: package
      - persist_to_workspace:
          root: ~/package
          paths:
            - dvmone-*

  unpack_package:
    steps:
      - attach_workspace:
          at: ~/package
      - run:
          name: "Unpack dvmone"
          working_directory: ~/package
          command: tar xz < dvmone*.tar.gz

jobs:

  lchar:
    executor: lchar
    steps:
    - checkout
    - run:
        name: "Check code format"
        command: |
          clang-format --version
          find include lib test -name '*.hpp' -o -name '*.cpp' -o -name '*.h' -o -name '*.c' | xargs clang-format -i
          git diff --color --exit-code
    - run:
        name: "Check spelling"
        command: |
          codespell --quiet-level=4 --skip=.git

  release-linux:
    executor: linux-gcc-latest
    environment:
      BUILD_TYPE: Release
    steps:
      - build
      - test
      - package

  release-macos:
    executor: macos
    environment:
      BUILD_TYPE: Release
    steps:
      - run:
          name: "Install System Dependencies"
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
      - build
      - test
      - package

  deploy:
    docker:
      - image: circleci/golang
    steps:
      - run:
          name: "Install GHR"
          command: |
            GO111MODULE=on go get github.com/tcnksm/ghr@v0.12.1
      - attach_workspace:
          at: ~/package
      - run:
          name: "Create GitHub release"
          command: |
            ls -l ~/package
            prerelease_flag=$([[ $CIRCLE_TAG =~ ^v[0-9\.]+$ ]] || echo '-prerelease')
            name="$CIRCLE_PROJECT_REPONAME ${CIRCLE_TAG:1}"
            echo $name
            ghr -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -n "$name" $prerelease_flag $CIRCLE_TAG ~/package

  consensus-tests:
    executor: consensus-tests
    environment:
      BUILD_TYPE: Coverage
      CMAKE_OPTIONS: -DDVMONE_TESTING=OFF -DCMAKE_CXX_FLAGS=-Og
    steps:
      - build
      - build_silkworm:
          commit: c75b07d26f19d1ce8439f9e73612cecf70dccaea
      - download_consensus_tests:
          rev: v10.3
      - run:
          name: "Silkworm-driven consensus tests (Advanced)"
          working_directory: ~/build
          no_output_timeout: 20m
          command: ~/silkworm/consensus --dvm lib/libdvmone.so,O=2 --tests ~/tests --threads $CMAKE_BUILD_PARALLEL_LEVEL
      - run:
          name: "Silkworm-driven consensus tests (Baseline)"
          working_directory: ~/build
          no_output_timeout: 20m
          command: ~/silkworm/consensus --dvm lib/libdvmone.so,O=0 --tests ~/tests --threads $CMAKE_BUILD_PARALLEL_LEVEL
      - collect_coverage_gcc
      - upload_coverage:
          flags: consensus

  gcc-min:
    executor: linux-gcc-min
    steps:
      - build
      - test

  clang-min:
    executor: linux-clang-min
    steps:
      - build
      - test


  gcc-latest-coverage:
    executor: linux-gcc-latest
    environment:
      BUILD_TYPE: Coverage
      TESTS_FILTER: unittests|charegration
    steps:
      - build
      - test
      - collect_coverage_gcc
      - upload_coverage:
          flags: unittests

  gcc-latest-memcheck:
    executor: linux-gcc-latest
    environment:
      BUILD_TYPE: Debug
      CMAKE_OPTIONS: -DCMAKE_CXX_FLAGS=-O1
    steps:
      - build
      - test
      - run:
          name: "Install valgrind"
          command: sudo apt-get -q update && sudo apt-get -qy install --no-install-recommends valgrind
      - run:
          name: "memcheck"
          working_directory: ~/build
          command: valgrind --vgdb=no --error-exitcode=99 bin/dvmone-unittests

  gcc-32bit:
    docker:
      - image: blastdoor7/cpp-build-env:17-gcc-11-multilib
    resource_class: small
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
      TOOLCHAIN: cxx17-32bit
    steps:
      - build
      - test

  clang-latest-sanitizers:
    executor: linux-clang-latest
    environment:
      CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=NO -DSANITIZE=address,undefined,shift-exponent,implicit-conversion,nullability -DCMAKE_CXX_CLANG_TIDY=clang-tidy
      UBSAN_OPTIONS: halt_on_error=1
    steps:
      - build
      - test

  clang-latest-coverage:
    executor: linux-clang-latest
    resource_class: small
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
      BUILD_TYPE: Coverage
      TESTS_FILTER: unittests|charegration
    steps:
      - build
      # TODO: use `test` command
      - run:
          name: "Run unit tests"
          working_directory: ~/build
          command: |
            bin/dvmone-unittests
      - run:
          name: "Coverage report"
          working_directory: ~/build
          command: |
            ARGS='lib/libdvmone.so -Xdemangler llvm-cxxfilt -instr-profile=dvmone.profdata -ignore-filename-regex=include/dvmc'
            SHOW_ARGS='-format=html -show-branches=count -show-regions -show-expansions'
            
            mkdir ~/coverage
            llvm-profdata merge *.profraw -o dvmone.profdata
            llvm-cov show $ARGS $SHOW_ARGS > ~/coverage/full.html
            llvm-cov show $ARGS $SHOW_ARGS -region-coverage-lt=100 > ~/coverage/missing.html

            llvm-cov report $ARGS > ~/coverage/report.txt
            llvm-cov report $ARGS -use-color
      - store_artifacts:
          path: ~/coverage
          destination: coverage



  macos-asan:
    executor: macos
    environment:
      BUILD_TYPE: RelWithDebInfo
      CMAKE_OPTIONS: -DSANITIZE=address
      TESTS_FILTER: unittests
    steps:
      - run:
          name: "Install System Dependencies"
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
      - build
      - test

workflows:
  version: 2
  dvmone:
    jobs:
      - lchar
      - release-linux:
          filters:
            tags:
              only: /.*/
      - release-macos:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - release-linux
            - release-macos
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9].*/
      - consensus-tests
      - gcc-min
      - clang-min
      - gcc-latest-coverage
      - gcc-latest-memcheck
      - clang-latest-sanitizers
      - clang-latest-coverage
      - macos-asan
      - gcc-32bit
